# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 759e0d44b61e6e80434e0410ec72d4dcf4c27db2b724bd692253b332b455412d47b7facb583de6485bd398ad0c99d717173d5270f39841b7a446cb2893ebcbf8
  facebook_id: "723160231162405"
  facebook_secret: "3916d70fadc7e1a082bd0130c36721ff"
  github_id: "4b897449cf22a8ffc7c5"
  github_secret: "3d11ab8c6ac3fbd42207c7ec6e2ae320142df478"
test:
  secret_key_base: 8ab93f18c603362dbf9b2f58c562dc11855e3fb68462b0a53a0e46dd09d820e74a63eaf31ebba67827ab2c1f74e19abdbdbda49434393db72fcc8697ca7af041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_id: "194553537542992"
  facebook_secret: "58010bc033b5a375c0f80f885d0d3ef5"
  github_id: "404359b98e6c8cfde6ab"
  github_secret: "1d7f0b01f0f4cd0760759ceb963c126b0a58d2a4"